# Generated by Django 5.0.3 on 2024-03-28 14:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=255, verbose_name="Место действия"),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                (
                    "nice_feeling",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятного чувства"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "once a week"), (2, "every day")],
                        default=2,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.timedelta(seconds=500)
                            )
                        ],
                        verbose_name="Время завершения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чувство",
                "verbose_name_plural": "Чувства",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                (
                    "nice_feeling",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятного чувства"
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=7, verbose_name="Частота выполнения привычки"
                    ),
                ),
                (
                    "last_completed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последний срок"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
